GET http://localhost:5000/api/v1/user/a

###

POST http://localhost:5000/api/v1/auth/register
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password": "123456"
}
###
POST http://localhost:5001/api/v1/auth/login
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password": "123456"
}

###
GET http://localhost:5000/api/v1/user/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTAsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwicm9sZV9jb2RlIjoiUjIiLCJpYXQiOjE3MjQyMTIzMDEsImV4cCI6MTcyNDY0NDMwMX0.TBfAUfz8hJ9l4ysGMG3Ha3qvy5PfLOMHb62izgdii9A

###
POST http://localhost:5000/api/v1/insert/


###
GET http://localhost:5000/api/v1/book/getbook/?available[]=123&available[]=123

###
GET http://localhost:5000/api/v1/book/